In [70]:
from engine import Value
from mlp import MLP, Layer, Neuron
import numpy as np
import random

In [26]:

# 5X5 image
image = np.array([[4,5,4,4,4],
         [4,5,4,4,4],
         [4,5,4,4,4],
         [4,5,4,4,4],
         [4,5,4,4,4]])

print(image)

# image = np.random.randn(5,5,1)

# print(image, image.shape)

[[4 5 4 4 4]
 [4 5 4 4 4]
 [4 5 4 4 4]
 [4 5 4 4 4]
 [4 5 4 4 4]]


In [27]:
# 2X2 filter
filter = np.array([[3,1],
          [4,5]])

print(filter)

# filter = np.random.randn(2,2)

# print(filter, filter.shape)

[[3 1]
 [4 5]]


In [55]:
# conv operation

def conv(image, filter):
    final_image_size = int(image.shape[0] - filter.shape[0] + 1)
    # print(final_image_size, type(final_image_size))
    final_image = np.zeros([final_image_size, final_image_size], dtype=float)
    
    for i in range(final_image_size):
        # print(i)
        for j in range(final_image_size):
            # Apply the filter to the current position
            for x in range(filter.shape[0]):
                for y in range(filter.shape[1]):
                    # print(final_image)
                    if i+x < image.shape[0] and j+y < image.shape[1]:
                        final_image[i][j] += image[i+x][j+y] * filter[x][y]
            
    return final_image

conv(image, filter)

array([[58., 59., 52., 52.],
       [58., 59., 52., 52.],
       [58., 59., 52., 52.],
       [58., 59., 52., 52.]])

In [69]:
import time

def flatten(image):
    height = image.shape[0]
    width = image.shape[1]

    flat_array = []

    flat_array = [0]*(height*width)
    cnt = 0

    for i in range(height):
        for j in range(width):
            flat_array[cnt] = image[i,j]
            cnt += 1

    return flat_array

flatten(image)

[4, 5, 4, 4, 4, 4, 5, 4, 4, 4, 4, 5, 4, 4, 4, 4, 5, 4, 4, 4, 4, 5, 4, 4, 4]

In [75]:
def CNN(input_image):
    filter = np.array([[3,1],
                        [4,5]])
    
    convoluted_image = conv(input_image, filter)
    flattened_image = flatten(convoluted_image)
    fc_model = MLP(len(flattened_image), [16, 16, 1])
    outputs = fc_model(flattened_image)

    return outputs


CNN(image)

Value(data=0.9403995243705735)